# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import checkpoint_pb2 as checkpoint__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in checkpoint_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CheckpointServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCheckpointTarget = channel.unary_unary(
                '/dtr.checkpoint.v1.CheckpointService/RegisterCheckpointTarget',
                request_serializer=checkpoint__pb2.RegisterCheckpointTargetRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.RegisterCheckpointTargetResponse.FromString,
                _registered_method=True)
        self.BeginCheckpoint = channel.unary_unary(
                '/dtr.checkpoint.v1.CheckpointService/BeginCheckpoint',
                request_serializer=checkpoint__pb2.BeginCheckpointRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.BeginCheckpointResponse.FromString,
                _registered_method=True)
        self.ReportChunk = channel.unary_unary(
                '/dtr.checkpoint.v1.CheckpointService/ReportChunk',
                request_serializer=checkpoint__pb2.ReportChunkRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.ReportChunkResponse.FromString,
                _registered_method=True)
        self.CommitCheckpoint = channel.unary_unary(
                '/dtr.checkpoint.v1.CheckpointService/CommitCheckpoint',
                request_serializer=checkpoint__pb2.CommitCheckpointRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.CommitCheckpointResponse.FromString,
                _registered_method=True)
        self.AbortCheckpoint = channel.unary_unary(
                '/dtr.checkpoint.v1.CheckpointService/AbortCheckpoint',
                request_serializer=checkpoint__pb2.AbortCheckpointRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.AbortCheckpointResponse.FromString,
                _registered_method=True)
        self.GetLatestManifest = channel.unary_unary(
                '/dtr.checkpoint.v1.CheckpointService/GetLatestManifest',
                request_serializer=checkpoint__pb2.GetLatestManifestRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.GetLatestManifestResponse.FromString,
                _registered_method=True)


class CheckpointServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def RegisterCheckpointTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginCheckpoint(self, request, context):
        """Open (or join) the barrier for a step. Idempotent per (target, step).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportChunk(self, request, context):
        """Report uploaded chunk integrity metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitCheckpoint(self, request, context):
        """Attempt to verify + publish the manifest once the quorum is satisfied.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortCheckpoint(self, request, context):
        """Abandon a checkpoint attempt; tmp data becomes GC-eligible.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestManifest(self, request, context):
        """Recovery entry point: fetch the newest committed manifest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckpointServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCheckpointTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCheckpointTarget,
                    request_deserializer=checkpoint__pb2.RegisterCheckpointTargetRequest.FromString,
                    response_serializer=checkpoint__pb2.RegisterCheckpointTargetResponse.SerializeToString,
            ),
            'BeginCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginCheckpoint,
                    request_deserializer=checkpoint__pb2.BeginCheckpointRequest.FromString,
                    response_serializer=checkpoint__pb2.BeginCheckpointResponse.SerializeToString,
            ),
            'ReportChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportChunk,
                    request_deserializer=checkpoint__pb2.ReportChunkRequest.FromString,
                    response_serializer=checkpoint__pb2.ReportChunkResponse.SerializeToString,
            ),
            'CommitCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitCheckpoint,
                    request_deserializer=checkpoint__pb2.CommitCheckpointRequest.FromString,
                    response_serializer=checkpoint__pb2.CommitCheckpointResponse.SerializeToString,
            ),
            'AbortCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortCheckpoint,
                    request_deserializer=checkpoint__pb2.AbortCheckpointRequest.FromString,
                    response_serializer=checkpoint__pb2.AbortCheckpointResponse.SerializeToString,
            ),
            'GetLatestManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestManifest,
                    request_deserializer=checkpoint__pb2.GetLatestManifestRequest.FromString,
                    response_serializer=checkpoint__pb2.GetLatestManifestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dtr.checkpoint.v1.CheckpointService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dtr.checkpoint.v1.CheckpointService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckpointService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def RegisterCheckpointTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.checkpoint.v1.CheckpointService/RegisterCheckpointTarget',
            checkpoint__pb2.RegisterCheckpointTargetRequest.SerializeToString,
            checkpoint__pb2.RegisterCheckpointTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.checkpoint.v1.CheckpointService/BeginCheckpoint',
            checkpoint__pb2.BeginCheckpointRequest.SerializeToString,
            checkpoint__pb2.BeginCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.checkpoint.v1.CheckpointService/ReportChunk',
            checkpoint__pb2.ReportChunkRequest.SerializeToString,
            checkpoint__pb2.ReportChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.checkpoint.v1.CheckpointService/CommitCheckpoint',
            checkpoint__pb2.CommitCheckpointRequest.SerializeToString,
            checkpoint__pb2.CommitCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.checkpoint.v1.CheckpointService/AbortCheckpoint',
            checkpoint__pb2.AbortCheckpointRequest.SerializeToString,
            checkpoint__pb2.AbortCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.checkpoint.v1.CheckpointService/GetLatestManifest',
            checkpoint__pb2.GetLatestManifestRequest.SerializeToString,
            checkpoint__pb2.GetLatestManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
