# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x0b\x64tr.data.v1\"N\n\x12ListObjectsRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x15\n\rsession_token\x18\x02 \x01(\t\x12\x0e\n\x06prefix\x18\x03 \x01(\t\"-\n\nObjectInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nsize_bytes\x18\x02 \x01(\x04\"?\n\x13ListObjectsResponse\x12(\n\x07objects\x18\x01 \x03(\x0b\x32\x17.dtr.data.v1.ObjectInfo\"\x96\x01\n\x11ReadObjectRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x15\n\rsession_token\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x0e\n\x06offset\x18\x04 \x01(\x04\x12\x0e\n\x06length\x18\x05 \x01(\x04\x12\x13\n\x0b\x66rame_bytes\x18\x06 \x01(\x04\x12\x15\n\rprefetch_hint\x18\x07 \x03(\t\"+\n\x0bObjectFrame\x12\x0e\n\x06offset\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"y\n\x11UploadChunkHeader\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x15\n\rsession_token\x18\x02 \x01(\t\x12\x18\n\x10\x63heckpoint_token\x18\x03 \x01(\t\x12\x0c\n\x04rank\x18\x04 \x01(\r\x12\x12\n\npart_index\x18\x05 \x01(\r\"]\n\x12UploadChunkRequest\x12\x30\n\x06header\x18\x01 \x01(\x0b\x32\x1e.dtr.data.v1.UploadChunkHeaderH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x05\n\x03msg\"F\n\x13UploadChunkResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nsize_bytes\x18\x02 \x01(\x04\x12\x0e\n\x06sha256\x18\x03 \x01(\t2\x87\x02\n\x0b\x44\x61taService\x12P\n\x0bListObjects\x12\x1f.dtr.data.v1.ListObjectsRequest\x1a .dtr.data.v1.ListObjectsResponse\x12H\n\nReadObject\x12\x1e.dtr.data.v1.ReadObjectRequest\x1a\x18.dtr.data.v1.ObjectFrame0\x01\x12\\\n\x15UploadCheckpointChunk\x12\x1f.dtr.data.v1.UploadChunkRequest\x1a .dtr.data.v1.UploadChunkResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTOBJECTSREQUEST']._serialized_start=27
  _globals['_LISTOBJECTSREQUEST']._serialized_end=105
  _globals['_OBJECTINFO']._serialized_start=107
  _globals['_OBJECTINFO']._serialized_end=152
  _globals['_LISTOBJECTSRESPONSE']._serialized_start=154
  _globals['_LISTOBJECTSRESPONSE']._serialized_end=217
  _globals['_READOBJECTREQUEST']._serialized_start=220
  _globals['_READOBJECTREQUEST']._serialized_end=370
  _globals['_OBJECTFRAME']._serialized_start=372
  _globals['_OBJECTFRAME']._serialized_end=415
  _globals['_UPLOADCHUNKHEADER']._serialized_start=417
  _globals['_UPLOADCHUNKHEADER']._serialized_end=538
  _globals['_UPLOADCHUNKREQUEST']._serialized_start=540
  _globals['_UPLOADCHUNKREQUEST']._serialized_end=633
  _globals['_UPLOADCHUNKRESPONSE']._serialized_start=635
  _globals['_UPLOADCHUNKRESPONSE']._serialized_end=705
  _globals['_DATASERVICE']._serialized_start=708
  _globals['_DATASERVICE']._serialized_end=971
# @@protoc_insertion_point(module_scope)
