# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListObjects = channel.unary_unary(
                '/dtr.data.v1.DataService/ListObjects',
                request_serializer=data__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=data__pb2.ListObjectsResponse.FromString,
                _registered_method=True)
        self.ReadObject = channel.unary_stream(
                '/dtr.data.v1.DataService/ReadObject',
                request_serializer=data__pb2.ReadObjectRequest.SerializeToString,
                response_deserializer=data__pb2.ObjectFrame.FromString,
                _registered_method=True)
        self.UploadCheckpointChunk = channel.stream_unary(
                '/dtr.data.v1.DataService/UploadCheckpointChunk',
                request_serializer=data__pb2.UploadChunkRequest.SerializeToString,
                response_deserializer=data__pb2.UploadChunkResponse.FromString,
                _registered_method=True)


class DataServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def ListObjects(self, request, context):
        """Enumerate shard objects under a prefix.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadObject(self, request, context):
        """Stream an object (or byte range) through the runtime's cache.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadCheckpointChunk(self, request_iterator, context):
        """Stream one checkpoint chunk into the tmp area for the given barrier.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=data__pb2.ListObjectsRequest.FromString,
                    response_serializer=data__pb2.ListObjectsResponse.SerializeToString,
            ),
            'ReadObject': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadObject,
                    request_deserializer=data__pb2.ReadObjectRequest.FromString,
                    response_serializer=data__pb2.ObjectFrame.SerializeToString,
            ),
            'UploadCheckpointChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadCheckpointChunk,
                    request_deserializer=data__pb2.UploadChunkRequest.FromString,
                    response_serializer=data__pb2.UploadChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dtr.data.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dtr.data.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.data.v1.DataService/ListObjects',
            data__pb2.ListObjectsRequest.SerializeToString,
            data__pb2.ListObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dtr.data.v1.DataService/ReadObject',
            data__pb2.ReadObjectRequest.SerializeToString,
            data__pb2.ObjectFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadCheckpointChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dtr.data.v1.DataService/UploadCheckpointChunk',
            data__pb2.UploadChunkRequest.SerializeToString,
            data__pb2.UploadChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
