# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runtime_pb2 as runtime__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/dtr.runtime.v1.RuntimeService/RegisterWorker',
                request_serializer=runtime__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=runtime__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/dtr.runtime.v1.RuntimeService/Heartbeat',
                request_serializer=runtime__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=runtime__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.RegisterDataset = channel.unary_unary(
                '/dtr.runtime.v1.RuntimeService/RegisterDataset',
                request_serializer=runtime__pb2.RegisterDatasetRequest.SerializeToString,
                response_deserializer=runtime__pb2.RegisterDatasetResponse.FromString,
                _registered_method=True)
        self.AcquireShardLease = channel.unary_unary(
                '/dtr.runtime.v1.RuntimeService/AcquireShardLease',
                request_serializer=runtime__pb2.AcquireShardLeaseRequest.SerializeToString,
                response_deserializer=runtime__pb2.AcquireShardLeaseResponse.FromString,
                _registered_method=True)
        self.RenewShardLease = channel.unary_unary(
                '/dtr.runtime.v1.RuntimeService/RenewShardLease',
                request_serializer=runtime__pb2.RenewShardLeaseRequest.SerializeToString,
                response_deserializer=runtime__pb2.RenewShardLeaseResponse.FromString,
                _registered_method=True)
        self.ReleaseShardLease = channel.unary_unary(
                '/dtr.runtime.v1.RuntimeService/ReleaseShardLease',
                request_serializer=runtime__pb2.ReleaseShardLeaseRequest.SerializeToString,
                response_deserializer=runtime__pb2.ReleaseShardLeaseResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def RegisterWorker(self, request, context):
        """Join the job. Idempotent for the same (worker_id, rank).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Liveness signal; drives lease expiry and membership eviction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDataset(self, request, context):
        """Register (or look up) a dataset and its shard layout.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireShardLease(self, request, context):
        """Lease a shard range for reading. Leases are TTL-bound and renewable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewShardLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseShardLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=runtime__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=runtime__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=runtime__pb2.HeartbeatRequest.FromString,
                    response_serializer=runtime__pb2.HeartbeatResponse.SerializeToString,
            ),
            'RegisterDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataset,
                    request_deserializer=runtime__pb2.RegisterDatasetRequest.FromString,
                    response_serializer=runtime__pb2.RegisterDatasetResponse.SerializeToString,
            ),
            'AcquireShardLease': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireShardLease,
                    request_deserializer=runtime__pb2.AcquireShardLeaseRequest.FromString,
                    response_serializer=runtime__pb2.AcquireShardLeaseResponse.SerializeToString,
            ),
            'RenewShardLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewShardLease,
                    request_deserializer=runtime__pb2.RenewShardLeaseRequest.FromString,
                    response_serializer=runtime__pb2.RenewShardLeaseResponse.SerializeToString,
            ),
            'ReleaseShardLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseShardLease,
                    request_deserializer=runtime__pb2.ReleaseShardLeaseRequest.FromString,
                    response_serializer=runtime__pb2.ReleaseShardLeaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dtr.runtime.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dtr.runtime.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.runtime.v1.RuntimeService/RegisterWorker',
            runtime__pb2.RegisterWorkerRequest.SerializeToString,
            runtime__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.runtime.v1.RuntimeService/Heartbeat',
            runtime__pb2.HeartbeatRequest.SerializeToString,
            runtime__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.runtime.v1.RuntimeService/RegisterDataset',
            runtime__pb2.RegisterDatasetRequest.SerializeToString,
            runtime__pb2.RegisterDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireShardLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.runtime.v1.RuntimeService/AcquireShardLease',
            runtime__pb2.AcquireShardLeaseRequest.SerializeToString,
            runtime__pb2.AcquireShardLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewShardLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.runtime.v1.RuntimeService/RenewShardLease',
            runtime__pb2.RenewShardLeaseRequest.SerializeToString,
            runtime__pb2.RenewShardLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseShardLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dtr.runtime.v1.RuntimeService/ReleaseShardLease',
            runtime__pb2.ReleaseShardLeaseRequest.SerializeToString,
            runtime__pb2.ReleaseShardLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
