apiVersion: v1
kind: Service
metadata:
  name: {{ include "dtr-runtime.fullname" . }}
  labels:
    {{- include "dtr-runtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "dtr-runtime.selectorLabels" . | nindent 4 }}
